### ISSUE TITLE
No PIL package available in pypi

### ISSUE THREAD

**Issue by arnabdasgupta04** [delimitry/collage_maker#6]
![image](https://user-images.githubusercontent.com/63199431/200237361-fedd6186-bcdb-41f4-84e1-31e0d8523c1f.png)
Please find the above issue while using PIL , please see if your code can work with some other image library other than PIL and Image

**Comment by delimitry** [comment]
Hi, @arnabdasgupta04!
Please try to install Pillow: `pip install Pillow`.
